apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grpc
  annotations:
    github.com/project-slug: rsanchez-trv/grpc
  tags: ["custom-tag"]
spec:
  type: other
  lifecycle: unknown
  owner: team-a
